const products=[
        {id:'1',
        name:"1تاپ" ,
        price:30000,
        url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU'],
        amount: 1,
        colors:['مشکی','سفید','قرمز','ابی','صورتی'],
        color:'',
        subject:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, laudantium perspiciatis in inventore debitis voluptas quasi, nemo aspernatur sit, dolores'],
        size:['38','40','42','44','46','48','50','52','54'],
        siz:''
      },


        {id:'2',name:"تاپ2" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
        {id:'3',name:"تاپ3" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
        {id:'4',name:"تاپ4" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
        {id:'5',name:"تاپ5" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
        {id:'6',name:"تاپ6" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
        {id:'7',name:"تاپ7" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZqQrHEvTb-eZiiZSxHEiwGf4-oECErBjnQ&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
        
    {id:'8',name:"تیشرت1" ,price:50000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
    {id:'9',name:"تیشرت2" ,price:60000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
    {id:'10',name:"تیشرت3" ,price:80000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
    {id:'11',name:"تیشرت4" ,price:370000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
    {id:'12',name:"تیشرت5" ,price:90000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
    {id:'13',name:"تیشرت6" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
    {id:'14',name:"تیشرت7" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5sEeX7hPsivDs7udWhEvOMVaIwG9unkiKTw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      
      {id:'15',name:"تونیک1" ,price:60000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://setare.com/files/fa/news/1397/7/23https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'16',name:"تونیک2" ,price:80000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'17',name:"تونیک3" ,price:370000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'18',name:"تونیک4" ,price:90000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'19',name:"تونیک5" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ مناسب برای تمام سنین', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'20',name:"تونیک6" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'21',name:"تونیک7" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS701cx-SiqDH8XB02qz9HrQbE3KVNH-q9YRA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},

      {id:'22',name:"پیراهن زنانه1" ,price:6000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'23',name:"پیراهن زنانه2" ,price:80000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'24',name:"پیراهن زنانه3" ,price:370000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'25',name:"پیراهن زنانه4" ,price:90000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'26',name:"پیراهن زنانه5" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'27',name:"پیراهن زنانه6" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'28',name:"پیراهن زنانه7" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP-tNvJHm_KyzHwlo5CoTLrTanS0_-AtSFw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
       
      {id:'29',name:"شلوار زنانه1" ,price:6000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'30',name:"شلوار زنانه2" ,price:80000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'31',name:"شلوار زنانه3" ,price:370000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'32',name:"شلوار زنانه4" ,price:90000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'33',name:"شلوار زنانه5" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'34',name:"شلوار زنانه6" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'35',name:"شلوار زنانه7" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcAhEHy3g5D-TA22C27lZANkg4R-ueZ_u1w&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},

      {id:'36',name:"حراجی 1" ,price:6000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQetYCcmjSrqqbRY4Udj42nu2_pQIgKHbUAXw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQetYCcmjSrqqbRY4Udj42nu2_pQIgKHbUAXw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQetYCcmjSrqqbRY4Udj42nu2_pQIgKHbUAXw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'37',name:"حراجی 2" ,price:80000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-9MbVnxClo8tqJGz8klgGDk67VZjh1WBmig&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-9MbVnxClo8tqJGz8klgGDk67VZjh1WBmig&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-9MbVnxClo8tqJGz8klgGDk67VZjh1WBmig&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'38',name:"حراجی 3" ,price:370000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpUspWRB3YxBM5_6NAbhGfgtkw3ighihF7Qw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpUspWRB3YxBM5_6NAbhGfgtkw3ighihF7Qw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpUspWRB3YxBM5_6NAbhGfgtkw3ighihF7Qw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'39',name:"حراجی 4" ,price:90000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRiGrnBB1HL4JWdIjIaB0JO148WsMeYUTLAA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRiGrnBB1HL4JWdIjIaB0JO148WsMeYUTLAA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRiGrnBB1HL4JWdIjIaB0JO148WsMeYUTLAA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'40',name:"حراجی 5" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-greN8Nq4cXHY87JGqiF5n5vQaagjuiRf0g&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-greN8Nq4cXHY87JGqiF5n5vQaagjuiRf0g&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-greN8Nq4cXHY87JGqiF5n5vQaagjuiRf0g&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'41',name:"حراجی 6" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP6WxAIGnK2Fw01S48stkIdyb0DOJgOu-gLg&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP6WxAIGnK2Fw01S48stkIdyb0DOJgOu-gLg&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP6WxAIGnK2Fw01S48stkIdyb0DOJgOu-gLg&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'42',name:"حراجی 7" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc4E9H64jHRUGA8CxwzDe_pp8j_zeIc-rgPw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc4E9H64jHRUGA8CxwzDe_pp8j_zeIc-rgPw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc4E9H64jHRUGA8CxwzDe_pp8j_zeIc-rgPw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},

      {id:'43',name:"حراجی 1" ,price:6000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQetYCcmjSrqqbRY4Udj42nu2_pQIgKHbUAXw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQetYCcmjSrqqbRY4Udj42nu2_pQIgKHbUAXw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQetYCcmjSrqqbRY4Udj42nu2_pQIgKHbUAXw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'44',name:"حراجی 2" ,price:80000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-9MbVnxClo8tqJGz8klgGDk67VZjh1WBmig&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-9MbVnxClo8tqJGz8klgGDk67VZjh1WBmig&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-9MbVnxClo8tqJGz8klgGDk67VZjh1WBmig&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'45',name:"حراجی 3" ,price:370000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpUspWRB3YxBM5_6NAbhGfgtkw3ighihF7Qw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpUspWRB3YxBM5_6NAbhGfgtkw3ighihF7Qw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpUspWRB3YxBM5_6NAbhGfgtkw3ighihF7Qw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'46',name:"حراجی 4" ,price:90000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRiGrnBB1HL4JWdIjIaB0JO148WsMeYUTLAA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRiGrnBB1HL4JWdIjIaB0JO148WsMeYUTLAA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRiGrnBB1HL4JWdIjIaB0JO148WsMeYUTLAA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'47',name:"حراجی 5" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-greN8Nq4cXHY87JGqiF5n5vQaagjuiRf0g&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-greN8Nq4cXHY87JGqiF5n5vQaagjuiRf0g&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-greN8Nq4cXHY87JGqiF5n5vQaagjuiRf0g&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'48',name:"حراجی 6" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP6WxAIGnK2Fw01S48stkIdyb0DOJgOu-gLg&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP6WxAIGnK2Fw01S48stkIdyb0DOJgOu-gLg&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP6WxAIGnK2Fw01S48stkIdyb0DOJgOu-gLg&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'49',name:"حراجی 7" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc4E9H64jHRUGA8CxwzDe_pp8j_zeIc-rgPw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc4E9H64jHRUGA8CxwzDe_pp8j_zeIc-rgPw&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTc4E9H64jHRUGA8CxwzDe_pp8j_zeIc-rgPw&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},

      {id:'50',name:"تک ها 1" ,price:6000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqRh1uSF5Ps1iDP4OaNTBigUzMIHpjY6twGA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqRh1uSF5Ps1iDP4OaNTBigUzMIHpjY6twGA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqRh1uSF5Ps1iDP4OaNTBigUzMIHpjY6twGA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'51',name:"تک ها 2" ,price:80000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLVykopHgg6Exnde4pVBz7HSldErCFHST3Jg&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLVykopHgg6Exnde4pVBz7HSldErCFHST3Jg&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLVykopHgg6Exnde4pVBz7HSldErCFHST3Jg&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'52',name:"تک ها 3" ,price:370000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlHKmRhse_crv62KzvBHGyohanQmifoQBuFA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlHKmRhse_crv62KzvBHGyohanQmifoQBuFA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlHKmRhse_crv62KzvBHGyohanQmifoQBuFA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'53',name:"تک ها 4" ,price:90000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM3Jp0ayX1uqpXFEt5jL3PHVkG67E2QkddWA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM3Jp0ayX1uqpXFEt5jL3PHVkG67E2QkddWA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM3Jp0ayX1uqpXFEt5jL3PHVkG67E2QkddWA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'54',name:"تک ها 5" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5TrzDJTAWV2J6ZLbHNxUb93MywSMUNTchnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5TrzDJTAWV2J6ZLbHNxUb93MywSMUNTchnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5TrzDJTAWV2J6ZLbHNxUb93MywSMUNTchnQ&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'55',name:"تک ها 6" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbe_QljPYMZTzLa_Fxh93w3WLvxz8n1j3Y_Q&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbe_QljPYMZTzLa_Fxh93w3WLvxz8n1j3Y_Q&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbe_QljPYMZTzLa_Fxh93w3WLvxz8n1j3Y_Q&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'56',name:"تک ها 7" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmGkXsJwp0PKeJ7Ma_fdHYH2mr3YE5EGYh6g&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmGkXsJwp0PKeJ7Ma_fdHYH2mr3YE5EGYh6g&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmGkXsJwp0PKeJ7Ma_fdHYH2mr3YE5EGYh6g&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'57',name:"تک ها 1" ,price:6000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqRh1uSF5Ps1iDP4OaNTBigUzMIHpjY6twGA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqRh1uSF5Ps1iDP4OaNTBigUzMIHpjY6twGA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqRh1uSF5Ps1iDP4OaNTBigUzMIHpjY6twGA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'58',name:"تک ها 2" ,price:80000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLVykopHgg6Exnde4pVBz7HSldErCFHST3Jg&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLVykopHgg6Exnde4pVBz7HSldErCFHST3Jg&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLVykopHgg6Exnde4pVBz7HSldErCFHST3Jg&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'59',name:"تک ها 3" ,price:370000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlHKmRhse_crv62KzvBHGyohanQmifoQBuFA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlHKmRhse_crv62KzvBHGyohanQmifoQBuFA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlHKmRhse_crv62KzvBHGyohanQmifoQBuFA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'60',name:"تک ها 4" ,price:90000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM3Jp0ayX1uqpXFEt5jL3PHVkG67E2QkddWA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM3Jp0ayX1uqpXFEt5jL3PHVkG67E2QkddWA&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM3Jp0ayX1uqpXFEt5jL3PHVkG67E2QkddWA&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'61',name:"تک ها 5" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5TrzDJTAWV2J6ZLbHNxUb93MywSMUNTchnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5TrzDJTAWV2J6ZLbHNxUb93MywSMUNTchnQ&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5TrzDJTAWV2J6ZLbHNxUb93MywSMUNTchnQ&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'62',name:"تک ها 6" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbe_QljPYMZTzLa_Fxh93w3WLvxz8n1j3Y_Q&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbe_QljPYMZTzLa_Fxh93w3WLvxz8n1j3Y_Q&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbe_QljPYMZTzLa_Fxh93w3WLvxz8n1j3Y_Q&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''},
      {id:'63',name:"تک ها 7" ,price:30000,url:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmGkXsJwp0PKeJ7Ma_fdHYH2mr3YE5EGYh6g&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmGkXsJwp0PKeJ7Ma_fdHYH2mr3YE5EGYh6g&usqp=CAU','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmGkXsJwp0PKeJ7Ma_fdHYH2mr3YE5EGYh6g&usqp=CAU'], amount: 1,colors:['مشکی','سفید','قرمز','ابی','صورتی'],color:'',subject:'جنس:نخ', size:['38','40','42','44','46','48','50','52','54'], siz:''}
];
    

 
export default products;

